pipeline:
  build:
    image: maven:3.5.0-jdk-8-alpine
    commands:
      - mvn clean install
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: general
